"""Add manuscript management system tables

Revision ID: 14829c1bc116
Revises: 44ae7610c61f
Create Date: 2025-11-14 15:15:44.981750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14829c1bc116'
down_revision: Union[str, Sequence[str], None] = '44ae7610c61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliations_name'), 'affiliations', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('expertise_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['expertise_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expertise_domains_name'), 'expertise_domains', ['name'], unique=True)
    op.create_table('journal_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_configs_key'), 'journal_configs', ['key'], unique=True)
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratories_name'), 'laboratories', ['name'], unique=True)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('review_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('structure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_forms_name'), 'review_forms', ['name'], unique=False)
    op.create_table('editor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editor_assignments_laboratory_id'), 'editor_assignments', ['laboratory_id'], unique=False)
    op.create_index(op.f('ix_editor_assignments_user_id'), 'editor_assignments', ['user_id'], unique=False)
    op.create_table('manuscripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('last_revision_at', sa.DateTime(), nullable=True),
    sa.Column('decision_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscripts_author_id'), 'manuscripts', ['author_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_status'), 'manuscripts', ['status'], unique=False)
    op.create_index(op.f('ix_manuscripts_title'), 'manuscripts', ['title'], unique=False)
    op.create_table('user_affiliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_affiliations_affiliation_id'), 'user_affiliations', ['affiliation_id'], unique=False)
    op.create_index(op.f('ix_user_affiliations_user_id'), 'user_affiliations', ['user_id'], unique=False)
    op.create_table('user_expertise_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expertise_domain_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expertise_domain_id'], ['expertise_domains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_expertise_domains_expertise_domain_id'), 'user_expertise_domains', ['expertise_domain_id'], unique=False)
    op.create_index(op.f('ix_user_expertise_domains_user_id'), 'user_expertise_domains', ['user_id'], unique=False)
    op.create_table('user_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_languages_language_id'), 'user_languages', ['language_id'], unique=False)
    op.create_index(op.f('ix_user_languages_user_id'), 'user_languages', ['user_id'], unique=False)
    op.create_table('manuscript_discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['manuscript_discussions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_discussions_manuscript_id'), 'manuscript_discussions', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_manuscript_discussions_user_id'), 'manuscript_discussions', ['user_id'], unique=False)
    op.create_table('manuscript_editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_editors_editor_id'), 'manuscript_editors', ['editor_id'], unique=False)
    op.create_index(op.f('ix_manuscript_editors_manuscript_id'), 'manuscript_editors', ['manuscript_id'], unique=False)
    op.create_table('manuscript_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_files_manuscript_id'), 'manuscript_files', ['manuscript_id'], unique=False)
    op.create_table('manuscript_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changes_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_versions_manuscript_id'), 'manuscript_versions', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_manuscript_versions_version_number'), 'manuscript_versions', ['version_number'], unique=False)
    op.create_table('mentorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorships_manuscript_id'), 'mentorships', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_mentorships_mentee_id'), 'mentorships', ['mentee_id'], unique=False)
    op.create_index(op.f('ix_mentorships_mentor_id'), 'mentorships', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentorships_status'), 'mentorships', ['status'], unique=False)
    op.create_table('review_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('invitation_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decline_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_assignments_manuscript_id'), 'review_assignments', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_review_assignments_reviewer_id'), 'review_assignments', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_assignments_status'), 'review_assignments', ['status'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('decision_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internal_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_decision'), 'review_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_review_decisions_manuscript_id'), 'review_decisions', ['manuscript_id'], unique=False)
    op.create_table('mentorship_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentorship_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activity_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_activity_logs_activity_type'), 'mentorship_activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_mentorship_activity_logs_mentorship_id'), 'mentorship_activity_logs', ['mentorship_id'], unique=False)
    op.create_index(op.f('ix_mentorship_activity_logs_user_id'), 'mentorship_activity_logs', ['user_id'], unique=False)
    op.create_table('mentorship_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentorship_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_comments_mentorship_id'), 'mentorship_comments', ['mentorship_id'], unique=False)
    op.create_index(op.f('ix_mentorship_comments_user_id'), 'mentorship_comments', ['user_id'], unique=False)
    op.create_table('mentorship_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentorship_id', sa.Integer(), nullable=False),
    sa.Column('given_by', sa.Integer(), nullable=False),
    sa.Column('feedback_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['given_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_feedbacks_mentorship_id'), 'mentorship_feedbacks', ['mentorship_id'], unique=False)
    op.create_table('review_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_assignment_id', sa.Integer(), nullable=False),
    sa.Column('review_form_id', sa.Integer(), nullable=True),
    sa.Column('responses', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('overall_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidential_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_assignment_id'], ['review_assignments.id'], ),
    sa.ForeignKeyConstraint(['review_form_id'], ['review_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_responses_review_assignment_id'), 'review_responses', ['review_assignment_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_response_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_response_id'], ['review_responses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_review_response_id'), 'review_comments', ['review_response_id'], unique=False)
    op.create_index(op.f('ix_review_comments_user_id'), 'review_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_user_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_review_response_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_review_responses_review_assignment_id'), table_name='review_responses')
    op.drop_table('review_responses')
    op.drop_index(op.f('ix_mentorship_feedbacks_mentorship_id'), table_name='mentorship_feedbacks')
    op.drop_table('mentorship_feedbacks')
    op.drop_index(op.f('ix_mentorship_comments_user_id'), table_name='mentorship_comments')
    op.drop_index(op.f('ix_mentorship_comments_mentorship_id'), table_name='mentorship_comments')
    op.drop_table('mentorship_comments')
    op.drop_index(op.f('ix_mentorship_activity_logs_user_id'), table_name='mentorship_activity_logs')
    op.drop_index(op.f('ix_mentorship_activity_logs_mentorship_id'), table_name='mentorship_activity_logs')
    op.drop_index(op.f('ix_mentorship_activity_logs_activity_type'), table_name='mentorship_activity_logs')
    op.drop_table('mentorship_activity_logs')
    op.drop_index(op.f('ix_review_decisions_manuscript_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_decision'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_review_assignments_status'), table_name='review_assignments')
    op.drop_index(op.f('ix_review_assignments_reviewer_id'), table_name='review_assignments')
    op.drop_index(op.f('ix_review_assignments_manuscript_id'), table_name='review_assignments')
    op.drop_table('review_assignments')
    op.drop_index(op.f('ix_mentorships_status'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_mentor_id'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_mentee_id'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_manuscript_id'), table_name='mentorships')
    op.drop_table('mentorships')
    op.drop_index(op.f('ix_manuscript_versions_version_number'), table_name='manuscript_versions')
    op.drop_index(op.f('ix_manuscript_versions_manuscript_id'), table_name='manuscript_versions')
    op.drop_table('manuscript_versions')
    op.drop_index(op.f('ix_manuscript_files_manuscript_id'), table_name='manuscript_files')
    op.drop_table('manuscript_files')
    op.drop_index(op.f('ix_manuscript_editors_manuscript_id'), table_name='manuscript_editors')
    op.drop_index(op.f('ix_manuscript_editors_editor_id'), table_name='manuscript_editors')
    op.drop_table('manuscript_editors')
    op.drop_index(op.f('ix_manuscript_discussions_user_id'), table_name='manuscript_discussions')
    op.drop_index(op.f('ix_manuscript_discussions_manuscript_id'), table_name='manuscript_discussions')
    op.drop_table('manuscript_discussions')
    op.drop_index(op.f('ix_user_languages_user_id'), table_name='user_languages')
    op.drop_index(op.f('ix_user_languages_language_id'), table_name='user_languages')
    op.drop_table('user_languages')
    op.drop_index(op.f('ix_user_expertise_domains_user_id'), table_name='user_expertise_domains')
    op.drop_index(op.f('ix_user_expertise_domains_expertise_domain_id'), table_name='user_expertise_domains')
    op.drop_table('user_expertise_domains')
    op.drop_index(op.f('ix_user_affiliations_user_id'), table_name='user_affiliations')
    op.drop_index(op.f('ix_user_affiliations_affiliation_id'), table_name='user_affiliations')
    op.drop_table('user_affiliations')
    op.drop_index(op.f('ix_manuscripts_title'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_status'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_author_id'), table_name='manuscripts')
    op.drop_table('manuscripts')
    op.drop_index(op.f('ix_editor_assignments_user_id'), table_name='editor_assignments')
    op.drop_index(op.f('ix_editor_assignments_laboratory_id'), table_name='editor_assignments')
    op.drop_table('editor_assignments')
    op.drop_index(op.f('ix_review_forms_name'), table_name='review_forms')
    op.drop_table('review_forms')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_laboratories_name'), table_name='laboratories')
    op.drop_table('laboratories')
    op.drop_index(op.f('ix_journal_configs_key'), table_name='journal_configs')
    op.drop_table('journal_configs')
    op.drop_index(op.f('ix_expertise_domains_name'), table_name='expertise_domains')
    op.drop_table('expertise_domains')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_affiliations_name'), table_name='affiliations')
    op.drop_table('affiliations')
    # ### end Alembic commands ###
