"""auto_migration_20251226_155634

Revision ID: 275674b3b5ec
Revises: 58d54ef68f0c
Create Date: 2025-12-26 14:56:38.437743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '275674b3b5ec'
down_revision: Union[str, Sequence[str], None] = '58d54ef68f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('date_limite', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'date_limite')
    # ### end Alembic commands ###
