"""auto_migration_20251109_192232

Revision ID: 478bc5319dd6
Revises: e7bf4273b72e
Create Date: 2025-11-09 18:22:34.365841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '478bc5319dd6'
down_revision: Union[str, Sequence[str], None] = 'e7bf4273b72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
