"""add_otp_and_reset_password_fields

Revision ID: 58d54ef68f0c
Revises: 20251225_190832
Create Date: 2025-12-26 13:13:57.820044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58d54ef68f0c'
down_revision: Union[str, Sequence[str], None] = '20251225_190832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manuscript_annotations', 'comment',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('manuscript_annotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('manuscript_annotations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_manuscript_annotations_evaluator'), table_name='manuscript_annotations')
    op.drop_index(op.f('idx_manuscript_annotations_manuscript'), table_name='manuscript_annotations')
    op.create_index(op.f('ix_manuscript_annotations_evaluator_id'), 'manuscript_annotations', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_manuscript_annotations_manuscript_id'), 'manuscript_annotations', ['manuscript_id'], unique=False)
    op.alter_column('manuscript_evaluation_grids', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('manuscript_evaluation_grids', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('manuscript_evaluation_grids', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_evaluation_grids_evaluator'), table_name='manuscript_evaluation_grids')
    op.drop_index(op.f('idx_evaluation_grids_manuscript'), table_name='manuscript_evaluation_grids')
    op.create_index(op.f('ix_manuscript_evaluation_grids_evaluator_id'), 'manuscript_evaluation_grids', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_manuscript_evaluation_grids_manuscript_id'), 'manuscript_evaluation_grids', ['manuscript_id'], unique=False)
    op.drop_constraint(op.f('manuscript_evaluation_grids_evaluator_id_fkey'), 'manuscript_evaluation_grids', type_='foreignkey')
    op.drop_constraint(op.f('manuscript_evaluation_grids_manuscript_id_fkey'), 'manuscript_evaluation_grids', type_='foreignkey')
    op.create_foreign_key(None, 'manuscript_evaluation_grids', 'manuscripts', ['manuscript_id'], ['id'])
    op.create_foreign_key(None, 'manuscript_evaluation_grids', 'users', ['evaluator_id'], ['id'])
    op.alter_column('manuscripts', 'anonymized_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('users', sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_send_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_otp_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'last_otp_sent_at')
    op.drop_column('users', 'otp_send_count')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    op.alter_column('manuscripts', 'anonymized_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'manuscript_evaluation_grids', type_='foreignkey')
    op.drop_constraint(None, 'manuscript_evaluation_grids', type_='foreignkey')
    op.create_foreign_key(op.f('manuscript_evaluation_grids_manuscript_id_fkey'), 'manuscript_evaluation_grids', 'manuscripts', ['manuscript_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('manuscript_evaluation_grids_evaluator_id_fkey'), 'manuscript_evaluation_grids', 'users', ['evaluator_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_manuscript_evaluation_grids_manuscript_id'), table_name='manuscript_evaluation_grids')
    op.drop_index(op.f('ix_manuscript_evaluation_grids_evaluator_id'), table_name='manuscript_evaluation_grids')
    op.create_index(op.f('idx_evaluation_grids_manuscript'), 'manuscript_evaluation_grids', ['manuscript_id'], unique=False)
    op.create_index(op.f('idx_evaluation_grids_evaluator'), 'manuscript_evaluation_grids', ['evaluator_id'], unique=False)
    op.alter_column('manuscript_evaluation_grids', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('manuscript_evaluation_grids', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('manuscript_evaluation_grids', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_manuscript_annotations_manuscript_id'), table_name='manuscript_annotations')
    op.drop_index(op.f('ix_manuscript_annotations_evaluator_id'), table_name='manuscript_annotations')
    op.create_index(op.f('idx_manuscript_annotations_manuscript'), 'manuscript_annotations', ['manuscript_id'], unique=False)
    op.create_index(op.f('idx_manuscript_annotations_evaluator'), 'manuscript_annotations', ['evaluator_id'], unique=False)
    op.alter_column('manuscript_annotations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('manuscript_annotations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('manuscript_annotations', 'comment',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
