"""add_timestamps_and_last_name

Revision ID: 64d1cf6ad818
Revises: 478bc5319dd6
Create Date: 2025-11-09 18:56:47.414825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64d1cf6ad818'
down_revision: Union[str, Sequence[str], None] = '478bc5319dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('student', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('student', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('student', 'updated_at')
    op.drop_column('student', 'created_at')
    op.drop_column('student', 'last_name')
    # ### end Alembic commands ###
