"""auto_migration_20260110_091513

Revision ID: 72afff0c6ff9
Revises: e2a798cb3f4f
Create Date: 2026-01-10 09:15:15.626479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72afff0c6ff9'
down_revision: Union[str, Sequence[str], None] = 'e2a798cb3f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuscripts', sa.Column('docx_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manuscripts', 'docx_filename')
    # ### end Alembic commands ###
