"""dfdf

Revision ID: 748d0e635b9b
Revises: 48a43c459497
Create Date: 2025-11-09 18:14:57.211284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '748d0e635b9b'
down_revision: Union[str, Sequence[str], None] = '48a43c459497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'age')
    # ### end Alembic commands ###
