"""auto_migration_20251222_021118

Revision ID: afc265a757a5
Revises: a62e959897b1
Create Date: 2025-12-22 01:11:23.726719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afc265a757a5'
down_revision: Union[str, Sequence[str], None] = 'a62e959897b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Créer les types ENUM nécessaires
    editorrole = postgresql.ENUM('CHIEF_EDITOR', 'ASSOCIATE_EDITOR', 'HANDLING_EDITOR', 'SECTION_EDITOR', 'GUEST_EDITOR', name='editorrole')
    manuscriptfiletype = postgresql.ENUM('PDF', 'DOCX', 'TEX', 'SUPPLEMENTARY', 'COVER_LETTER', 'FIGURE', 'TABLE', 'DATA', 'OTHER', name='manuscriptfiletype')
    manuscriptstatus = postgresql.ENUM('SUBMITTED', 'UNDER_REVIEW', 'REVISED', 'ACCEPTED', 'REJECTED', 'REVISION_REQUESTED', 'PUBLISHED', name='manuscriptstatus')
    mentorshipactivitytype = postgresql.ENUM('COMMENT_ADDED', 'FEEDBACK_GIVEN', 'MILESTONE_REACHED', 'STATUS_CHANGED', 'MEETING_SCHEDULED', 'MEETING_COMPLETED', 'DOCUMENT_REVIEWED', 'GOAL_SET', 'GOAL_ACHIEVED', name='mentorshipactivitytype')
    mentorshipfeedbacktype = postgresql.ENUM('MILESTONE', 'PROGRESS_CHECK', 'FINAL_EVALUATION', 'INTERIM_REVIEW', 'IMPROVEMENT_PLAN', name='mentorshipfeedbacktype')
    mentorshipstatus = postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='mentorshipstatus')
    reviewassignmentstatus = postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='reviewassignmentstatus')
    reviewdecisiontype = postgresql.ENUM('ACCEPT', 'MINOR_REVISION', 'MAJOR_REVISION', 'REJECT', 'WITHDRAWN', name='reviewdecisiontype')
    reviewrecommendation = postgresql.ENUM('ACCEPT', 'MINOR_REVISION', 'MAJOR_REVISION', 'REJECT', name='reviewrecommendation')
    
    editorrole.create(op.get_bind(), checkfirst=True)
    manuscriptfiletype.create(op.get_bind(), checkfirst=True)
    manuscriptstatus.create(op.get_bind(), checkfirst=True)
    mentorshipactivitytype.create(op.get_bind(), checkfirst=True)
    mentorshipfeedbacktype.create(op.get_bind(), checkfirst=True)
    mentorshipstatus.create(op.get_bind(), checkfirst=True)
    reviewassignmentstatus.create(op.get_bind(), checkfirst=True)
    reviewdecisiontype.create(op.get_bind(), checkfirst=True)
    reviewrecommendation.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('signe_min', sa.Integer(), nullable=False),
    sa.Column('signe_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('signe_max > signe_min', name='check_signe_max_gt_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_name'), 'sections', ['name'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_title'), 'themes', ['title'], unique=False)
    op.create_table('manuscript_evaluators',
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('manuscript_id', 'evaluator_id')
    )
    op.create_index(op.f('ix_manuscript_evaluators_assigned_by_id'), 'manuscript_evaluators', ['assigned_by_id'], unique=False)
    
    # Supprimer d'abord la contrainte de clé étrangère dans review_responses
    op.drop_constraint('review_responses_review_form_id_fkey', 'review_responses', type_='foreignkey')
    
    # Maintenant on peut supprimer la table review_forms
    op.drop_index(op.f('ix_review_forms_name'), table_name='review_forms')
    op.drop_table('review_forms')
    
    op.alter_column('editor_assignments', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CHIEF_EDITOR', 'ASSOCIATE_EDITOR', 'HANDLING_EDITOR', 'SECTION_EDITOR', 'GUEST_EDITOR', name='editorrole'),
               existing_nullable=False,
               postgresql_using='role::editorrole')
    op.alter_column('languages', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('languages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('languages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('languages_code_key'), 'languages', type_='unique')
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.alter_column('manuscript_editors', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CHIEF_EDITOR', 'ASSOCIATE_EDITOR', 'HANDLING_EDITOR', 'SECTION_EDITOR', 'GUEST_EDITOR', name='editorrole'),
               existing_nullable=False,
               postgresql_using='role::editorrole')
    op.alter_column('manuscript_files', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PDF', 'DOCX', 'TEX', 'SUPPLEMENTARY', 'COVER_LETTER', 'FIGURE', 'TABLE', 'DATA', 'OTHER', name='manuscriptfiletype'),
               existing_nullable=False,
               postgresql_using='file_type::manuscriptfiletype')
    op.add_column('manuscripts', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.add_column('manuscripts', sa.Column('section_id', sa.Integer(), nullable=False))
    op.add_column('manuscripts', sa.Column('language_id', sa.Integer(), nullable=False))
    op.add_column('manuscripts', sa.Column('pdf_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.alter_column('manuscripts', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'REVISED', 'ACCEPTED', 'REJECTED', 'REVISION_REQUESTED', 'PUBLISHED', name='manuscriptstatus'),
               existing_nullable=False,
               postgresql_using='status::manuscriptstatus')
    op.alter_column('manuscripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('manuscripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_manuscripts_language_id'), 'manuscripts', ['language_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_section_id'), 'manuscripts', ['section_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_theme_id'), 'manuscripts', ['theme_id'], unique=False)
    op.drop_constraint(op.f('manuscripts_category_id_fkey'), 'manuscripts', type_='foreignkey')
    op.create_foreign_key(None, 'manuscripts', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'manuscripts', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(None, 'manuscripts', 'themes', ['theme_id'], ['id'])
    op.drop_column('manuscripts', 'submitted_at')
    op.drop_column('manuscripts', 'version')
    op.drop_column('manuscripts', 'category_id')
    op.drop_column('manuscripts', 'is_archived')
    op.drop_index(op.f('ix_mentor_assignments_author_active_unique'), table_name='mentor_assignments', postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_mentor_assignments_author_id_is_active'), table_name='mentor_assignments')
    op.create_index(op.f('ix_mentor_assignments_is_active'), 'mentor_assignments', ['is_active'], unique=False)
    op.alter_column('mentorship_activity_logs', 'activity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('COMMENT_ADDED', 'FEEDBACK_GIVEN', 'MILESTONE_REACHED', 'STATUS_CHANGED', 'MEETING_SCHEDULED', 'MEETING_COMPLETED', 'DOCUMENT_REVIEWED', 'GOAL_SET', 'GOAL_ACHIEVED', name='mentorshipactivitytype'),
               existing_nullable=False,
               postgresql_using='activity_type::mentorshipactivitytype')
    op.alter_column('mentorship_feedbacks', 'feedback_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MILESTONE', 'PROGRESS_CHECK', 'FINAL_EVALUATION', 'INTERIM_REVIEW', 'IMPROVEMENT_PLAN', name='mentorshipfeedbacktype'),
               existing_nullable=False,
               postgresql_using='feedback_type::mentorshipfeedbacktype')
    op.alter_column('mentorships', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='mentorshipstatus'),
               existing_nullable=False,
               postgresql_using='status::mentorshipstatus')
    op.drop_index(op.f('ix_mentorships_mentee_id'), table_name='mentorships')
    op.drop_constraint(op.f('mentorships_mentee_id_fkey'), 'mentorships', type_='foreignkey')
    op.drop_column('mentorships', 'mentee_id')
    op.alter_column('review_assignments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='reviewassignmentstatus'),
               existing_nullable=False,
               postgresql_using='status::reviewassignmentstatus')
    op.alter_column('review_decisions', 'decision',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACCEPT', 'MINOR_REVISION', 'MAJOR_REVISION', 'REJECT', 'WITHDRAWN', name='reviewdecisiontype'),
               existing_nullable=False,
               postgresql_using='decision::reviewdecisiontype')
    op.add_column('review_responses', sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('review_responses', 'recommendation',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACCEPT', 'MINOR_REVISION', 'MAJOR_REVISION', 'REJECT', name='reviewrecommendation'),
               existing_nullable=False,
               postgresql_using='recommendation::reviewrecommendation')
    op.drop_column('review_responses', 'review_form_id')
    op.drop_column('review_responses', 'responses')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('users_country_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_city_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'city_id')
    op.drop_column('users', 'country_id')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_city_id_fkey'), 'users', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(op.f('users_country_id_fkey'), 'users', 'countries', ['country_id'], ['id'])
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('review_responses', sa.Column('responses', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('review_responses', sa.Column('review_form_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('review_responses_review_form_id_fkey'), 'review_responses', 'review_forms', ['review_form_id'], ['id'])
    op.alter_column('review_responses', 'recommendation',
               existing_type=sa.Enum('ACCEPT', 'MINOR_REVISION', 'MAJOR_REVISION', 'REJECT', name='reviewrecommendation'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('review_responses', 'response')
    op.alter_column('review_decisions', 'decision',
               existing_type=sa.Enum('ACCEPT', 'MINOR_REVISION', 'MAJOR_REVISION', 'REJECT', 'WITHDRAWN', name='reviewdecisiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('review_assignments', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='reviewassignmentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('mentorships', sa.Column('mentee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('mentorships_mentee_id_fkey'), 'mentorships', 'users', ['mentee_id'], ['id'])
    op.create_index(op.f('ix_mentorships_mentee_id'), 'mentorships', ['mentee_id'], unique=False)
    op.alter_column('mentorships', 'status',
               existing_type=sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='mentorshipstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('mentorship_feedbacks', 'feedback_type',
               existing_type=sa.Enum('MILESTONE', 'PROGRESS_CHECK', 'FINAL_EVALUATION', 'INTERIM_REVIEW', 'IMPROVEMENT_PLAN', name='mentorshipfeedbacktype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('mentorship_activity_logs', 'activity_type',
               existing_type=sa.Enum('COMMENT_ADDED', 'FEEDBACK_GIVEN', 'MILESTONE_REACHED', 'STATUS_CHANGED', 'MEETING_SCHEDULED', 'MEETING_COMPLETED', 'DOCUMENT_REVIEWED', 'GOAL_SET', 'GOAL_ACHIEVED', name='mentorshipactivitytype'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_mentor_assignments_is_active'), table_name='mentor_assignments')
    op.create_index(op.f('ix_mentor_assignments_author_id_is_active'), 'mentor_assignments', ['author_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_mentor_assignments_author_active_unique'), 'mentor_assignments', ['author_id'], unique=True, postgresql_where='(is_active = true)')
    op.add_column('manuscripts', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('manuscripts', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('manuscripts', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manuscripts', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'manuscripts', type_='foreignkey')
    op.drop_constraint(None, 'manuscripts', type_='foreignkey')
    op.drop_constraint(None, 'manuscripts', type_='foreignkey')
    op.create_foreign_key(op.f('manuscripts_category_id_fkey'), 'manuscripts', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_manuscripts_theme_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_section_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_language_id'), table_name='manuscripts')
    op.alter_column('manuscripts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('manuscripts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('manuscripts', 'status',
               existing_type=sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'REVISED', 'ACCEPTED', 'REJECTED', 'REVISION_REQUESTED', 'PUBLISHED', name='manuscriptstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('manuscripts', 'pdf_filename')
    op.drop_column('manuscripts', 'language_id')
    op.drop_column('manuscripts', 'section_id')
    op.drop_column('manuscripts', 'theme_id')
    op.alter_column('manuscript_files', 'file_type',
               existing_type=sa.Enum('PDF', 'DOCX', 'TEX', 'SUPPLEMENTARY', 'COVER_LETTER', 'FIGURE', 'TABLE', 'DATA', 'OTHER', name='manuscriptfiletype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('manuscript_editors', 'role',
               existing_type=sa.Enum('CHIEF_EDITOR', 'ASSOCIATE_EDITOR', 'HANDLING_EDITOR', 'SECTION_EDITOR', 'GUEST_EDITOR', name='editorrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.create_unique_constraint(op.f('languages_code_key'), 'languages', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('languages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('languages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('languages', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('editor_assignments', 'role',
               existing_type=sa.Enum('CHIEF_EDITOR', 'ASSOCIATE_EDITOR', 'HANDLING_EDITOR', 'SECTION_EDITOR', 'GUEST_EDITOR', name='editorrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_table('review_forms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('structure', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('review_forms_pkey'))
    )
    op.create_index(op.f('ix_review_forms_name'), 'review_forms', ['name'], unique=False)
    op.drop_index(op.f('ix_manuscript_evaluators_assigned_by_id'), table_name='manuscript_evaluators')
    op.drop_table('manuscript_evaluators')
    op.drop_index(op.f('ix_themes_title'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_sections_name'), table_name='sections')
    op.drop_table('sections')
    
    # Supprimer les types ENUM
    postgresql.ENUM(name='editorrole').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='manuscriptfiletype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='manuscriptstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='mentorshipactivitytype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='mentorshipfeedbacktype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='mentorshipstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='reviewassignmentstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='reviewdecisiontype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='reviewrecommendation').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
