"""auto_migration_20260112_195044

Revision ID: c77ac1e477f8
Revises: 
Create Date: 2026-01-12 19:50:46.408256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c77ac1e477f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('signe_min', sa.Integer(), nullable=False),
    sa.Column('signe_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('signe_max > signe_min', name='check_signe_max_gt_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_name'), 'sections', ['name'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_limite', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_title'), 'themes', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('profile_photo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('orcid_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_send_count', sa.Integer(), nullable=False),
    sa.Column('last_otp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manuscripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'RE_SUBMITTED', 'UNDER_REVIEW', 'REVISED', 'ACCEPTED', 'REJECTED', 'REVISION_REQUESTED', 'PUBLISHED', name='manuscriptstatus'), nullable=False),
    sa.Column('evaluation_status', sa.String(length=50), nullable=False),
    sa.Column('pdf_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('docx_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_revision_at', sa.DateTime(), nullable=True),
    sa.Column('decision_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_anonymized', sa.Boolean(), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(), nullable=True),
    sa.Column('anonymized_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anonymized_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscripts_author_id'), 'manuscripts', ['author_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_evaluation_status'), 'manuscripts', ['evaluation_status'], unique=False)
    op.create_index(op.f('ix_manuscripts_is_anonymized'), 'manuscripts', ['is_anonymized'], unique=False)
    op.create_index(op.f('ix_manuscripts_language_id'), 'manuscripts', ['language_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_section_id'), 'manuscripts', ['section_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_status'), 'manuscripts', ['status'], unique=False)
    op.create_index(op.f('ix_manuscripts_theme_id'), 'manuscripts', ['theme_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_title'), 'manuscripts', ['title'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('manuscript_annotations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('annotation_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_by_role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x_position', sa.Float(), nullable=False),
    sa.Column('y_position', sa.Float(), nullable=False),
    sa.Column('position_data', sa.Text(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("annotation_type IN ('text', 'area', 'freetext', 'redaction')", name='check_annotation_type'),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_annotations_evaluator_id'), 'manuscript_annotations', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_manuscript_annotations_manuscript_id'), 'manuscript_annotations', ['manuscript_id'], unique=False)
    op.create_table('manuscript_evaluation_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('originality_of_ideas', sa.Text(), nullable=False),
    sa.Column('methodology_rigor', sa.Text(), nullable=False),
    sa.Column('theoretical_approach', sa.Text(), nullable=False),
    sa.Column('presentation_clarity', sa.Text(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('weaknesses', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manuscript_id', 'evaluator_id', name='uq_manuscript_evaluator')
    )
    op.create_index(op.f('ix_manuscript_evaluation_grids_evaluator_id'), 'manuscript_evaluation_grids', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_manuscript_evaluation_grids_manuscript_id'), 'manuscript_evaluation_grids', ['manuscript_id'], unique=False)
    op.create_table('manuscript_evaluators',
    sa.Column('manuscript_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='evaluatorassignmentstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('evaluation_deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('manuscript_id', 'evaluator_id')
    )
    op.create_index(op.f('ix_manuscript_evaluators_assigned_by_id'), 'manuscript_evaluators', ['assigned_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manuscript_evaluators_assigned_by_id'), table_name='manuscript_evaluators')
    op.drop_table('manuscript_evaluators')
    op.drop_index(op.f('ix_manuscript_evaluation_grids_manuscript_id'), table_name='manuscript_evaluation_grids')
    op.drop_index(op.f('ix_manuscript_evaluation_grids_evaluator_id'), table_name='manuscript_evaluation_grids')
    op.drop_table('manuscript_evaluation_grids')
    op.drop_index(op.f('ix_manuscript_annotations_manuscript_id'), table_name='manuscript_annotations')
    op.drop_index(op.f('ix_manuscript_annotations_evaluator_id'), table_name='manuscript_annotations')
    op.drop_table('manuscript_annotations')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_manuscripts_title'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_theme_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_status'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_section_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_language_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_is_anonymized'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_evaluation_status'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_author_id'), table_name='manuscripts')
    op.drop_table('manuscripts')
    op.drop_table('cities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_themes_title'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_sections_name'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_table('countries')
    # ### end Alembic commands ###
