"""
Auth Module Error Codes
Error codes specific to authentication and authorization
"""
from enum import Enum


class AuthErrorCode(str, Enum):
    """All codes in uppercase for consistency"""

    # Login/Authentication Errors
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD"

    # Token Errors
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_MISSING = "TOKEN_MISSING"
    INVALID_TOKEN_PAYLOAD = "INVALID_TOKEN_PAYLOAD"
    INVALID_TOKEN_FORMAT = "INVALID_TOKEN_FORMAT"
    INVALID_AUTHENTICATION_SCHEME = "INVALID_AUTHENTICATION_SCHEME"
    AUTHORIZATION_HEADER_MISSING = "AUTHORIZATION_HEADER_MISSING"

    # User Errors
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PASSWORD = "INVALID_PASSWORD"

    # Location Errors
    INVALID_COUNTRY_ID = "INVALID_COUNTRY_ID"
    INVALID_CITY_ID = "INVALID_CITY_ID"

    # Permission Errors
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    ROLE_REQUIRED = "ROLE_REQUIRED"
